[[pages]]
path = "Home.py"
name = "Dashboard"
icon = "ğŸ "

[[pages]]
path = "pages/system_details.py"
name = "System Details"
icon = "ğŸ’»"

[[pages]]
path = "pages/network_analysis.py"
name = "Network Analysis"
icon = "ğŸŒ"

[[pages]]
path = "pages/alerts_history.py"
name = "Alerts History"
icon = "âš ï¸"